/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: tc_db.proto */

#ifndef PROTOBUF_C_tc_5fdb_2eproto__INCLUDED
#define PROTOBUF_C_tc_5fdb_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct TcDb__TseDDLColumnDataTypeDef TcDb__TseDDLColumnDataTypeDef;
typedef struct TcDb__TseDDLColumnDef TcDb__TseDDLColumnDef;
typedef struct TcDb__TseDDLForeignKeyElementDef TcDb__TseDDLForeignKeyElementDef;
typedef struct TcDb__TseDDLForeignKeyDef TcDb__TseDDLForeignKeyDef;
typedef struct TcDb__TseDDLTableKeyPart TcDb__TseDDLTableKeyPart;
typedef struct TcDb__TseDDLTableKey TcDb__TseDDLTableKey;
typedef struct TcDb__TseMsgCommDef TcDb__TseMsgCommDef;
typedef struct TcDb__TseDDLPartitionTableDef TcDb__TseDDLPartitionTableDef;
typedef struct TcDb__TseDDLPartitionDef TcDb__TseDDLPartitionDef;
typedef struct TcDb__TseDDLCreateTableDef TcDb__TseDDLCreateTableDef;
typedef struct TcDb__TseDDLAlterTablePorp TcDb__TseDDLAlterTablePorp;
typedef struct TcDb__TseDDLAlterTableDrop TcDb__TseDDLAlterTableDrop;
typedef struct TcDb__TseDDLAlterTableDropKey TcDb__TseDDLAlterTableDropKey;
typedef struct TcDb__TseDDLAlterTableAlterColumn TcDb__TseDDLAlterTableAlterColumn;
typedef struct TcDb__TseDDLAlterTableDef TcDb__TseDDLAlterTableDef;
typedef struct TcDb__TseDDLTruncateTableDef TcDb__TseDDLTruncateTableDef;
typedef struct TcDb__TseDDLTruncateTablePartitionDef TcDb__TseDDLTruncateTablePartitionDef;
typedef struct TcDb__TseDDLRenameTableDef TcDb__TseDDLRenameTableDef;
typedef struct TcDb__TseDDLDropTableDef TcDb__TseDDLDropTableDef;
typedef struct TcDb__TseDDLAlterIndexDef TcDb__TseDDLAlterIndexDef;
typedef struct TcDb__TseDDLAutoExtendDef TcDb__TseDDLAutoExtendDef;
typedef struct TcDb__TseDDLDataFileDef TcDb__TseDDLDataFileDef;
typedef struct TcDb__TseDDLSpaceDef TcDb__TseDDLSpaceDef;
typedef struct TcDb__TseDDLDropSpaceDef TcDb__TseDDLDropSpaceDef;
typedef struct TcDb__TseDDLAlterSpaceDef TcDb__TseDDLAlterSpaceDef;


/* --- enums --- */


/* --- messages --- */

struct  TcDb__TseDDLColumnDataTypeDef
{
  ProtobufCMessage base;
  /*
   * These definitions is same as the `typmode_t`; thus they should
   * be replaced by typmode_t for unifying the definition of columns
   */
  /*
   * ct_type_t
   */
  int32_t datatype;
  uint32_t size;
  uint32_t precision;
  int32_t scale;
  int32_t mysql_ori_datatype;
};
#define TC_DB__TSE_DDLCOLUMN_DATA_TYPE_DEF__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tc_db__tse_ddlcolumn_data_type_def__descriptor) \
    , 0, 0, 0, 0, 0 }


struct  TcDb__TseDDLColumnDef
{
  ProtobufCMessage base;
  char *name;
  TcDb__TseDDLColumnDataTypeDef *datatype;
  uint32_t is_option_set;
  uint32_t col_id;
  char *cons_name;
  char *ref_user;
  char *ref_table;
  char *default_text;
  char *comment;
  /*
   * tse_alter_column_alter_mode
   */
  uint32_t alter_mode;
  uint64_t collate;
  char *new_name;
  uint32_t is_unsigned;
  char *default_func_name;
};
#define TC_DB__TSE_DDLCOLUMN_DEF__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tc_db__tse_ddlcolumn_def__descriptor) \
    , (char *)protobuf_c_empty_string, NULL, 0, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string }


struct  TcDb__TseDDLForeignKeyElementDef
{
  ProtobufCMessage base;
  char *src_column_name;
  char *ref_column_name;
};
#define TC_DB__TSE_DDLFOREIGN_KEY_ELEMENT_DEF__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tc_db__tse_ddlforeign_key_element_def__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  TcDb__TseDDLForeignKeyDef
{
  ProtobufCMessage base;
  /*
   * fill_dd_foreign_keys_from_create_fields
   */
  char *name;
  char *unique_index_name;
  uint32_t match_opt;
  uint32_t update_opt;
  uint32_t delete_opt;
  char *referenced_table_schema_name;
  char *referenced_table_name;
  size_t n_elements;
  TcDb__TseDDLForeignKeyElementDef **elements;
};
#define TC_DB__TSE_DDLFOREIGN_KEY_DEF__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tc_db__tse_ddlforeign_key_def__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0,NULL }


struct  TcDb__TseDDLTableKeyPart
{
  ProtobufCMessage base;
  /*
   * KEY_PART_INFO
   */
  char *name;
  /*
   * Length of key part in bytes, excluding NULL flag and length bytes 
   */
  uint32_t length;
  int32_t datatype;
  protobuf_c_boolean is_func;
  char *func_text;
  char *func_name;
  uint32_t is_unsigned;
};
#define TC_DB__TSE_DDLTABLE_KEY_PART__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tc_db__tse_ddltable_key_part__descriptor) \
    , (char *)protobuf_c_empty_string, 0, 0, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0 }


struct  TcDb__TseDDLTableKey
{
  ProtobufCMessage base;
  /*
   * Key
   */
  char *user;
  char *table;
  char *name;
  char *space;
  /*
   * tse_key_type
   */
  int32_t key_type;
  /*
   * tse_ha_key_alg
   */
  int32_t algorithm;
  protobuf_c_boolean is_func;
  size_t n_columns;
  TcDb__TseDDLTableKeyPart **columns;
  protobuf_c_boolean is_constraint;
  protobuf_c_boolean is_dsc;
};
#define TC_DB__TSE_DDLTABLE_KEY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tc_db__tse_ddltable_key__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0, 0, 0,NULL, 0, 0 }


struct  TcDb__TseMsgCommDef
{
  ProtobufCMessage base;
  uint32_t inst_id;
  uint32_t thd_id;
  uint32_t handler_id;
  uint64_t sess_addr;
};
#define TC_DB__TSE_MSG_COMM_DEF__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tc_db__tse_msg_comm_def__descriptor) \
    , 0, 0, 0, 0 }


struct  TcDb__TseDDLPartitionTableDef
{
  ProtobufCMessage base;
  char *name;
  size_t n_subpart_table_list;
  TcDb__TseDDLPartitionTableDef **subpart_table_list;
};
#define TC_DB__TSE_DDLPARTITION_TABLE_DEF__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tc_db__tse_ddlpartition_table_def__descriptor) \
    , (char *)protobuf_c_empty_string, 0,NULL }


struct  TcDb__TseDDLPartitionDef
{
  ProtobufCMessage base;
  uint32_t part_type;
  uint32_t subpart_type;
  size_t n_part_table_list;
  TcDb__TseDDLPartitionTableDef **part_table_list;
};
#define TC_DB__TSE_DDLPARTITION_DEF__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tc_db__tse_ddlpartition_def__descriptor) \
    , 0, 0, 0,NULL }


struct  TcDb__TseDDLCreateTableDef
{
  ProtobufCMessage base;
  char *schema;
  char *name;
  char *space;
  size_t n_columns;
  TcDb__TseDDLColumnDef **columns;
  size_t n_fk_list;
  TcDb__TseDDLForeignKeyDef **fk_list;
  size_t n_key_list;
  TcDb__TseDDLTableKey **key_list;
  /*
   *init auto incremnet value
   */
  uint64_t auto_increment_value;
  /*
   * if not exists
   */
  uint32_t options;
  char *db_name;
  char *sql_str;
  char *alter_table_name;
  char *alter_db_name;
  protobuf_c_boolean is_create_as_select;
  TcDb__TseDDLPartitionDef *partition_def;
};
#define TC_DB__TSE_DDLCREATE_TABLE_DEF__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tc_db__tse_ddlcreate_table_def__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0,NULL, 0,NULL, 0,NULL, 0, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, NULL }


struct  TcDb__TseDDLAlterTablePorp
{
  ProtobufCMessage base;
  /*
   * knl_alt_table_prop_t
   */
  char *new_name;
  uint32_t pctfree;
  uint32_t appendonly;
  uint32_t enable_row_move;
  uint32_t shrink_opt;
  int64_t serial_start;
};
#define TC_DB__TSE_DDLALTER_TABLE_PORP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tc_db__tse_ddlalter_table_porp__descriptor) \
    , (char *)protobuf_c_empty_string, 0, 0, 0, 0, 0 }


struct  TcDb__TseDDLAlterTableDrop
{
  ProtobufCMessage base;
  char *name;
  /*
   * tse_alter_table_drop_type
   */
  int32_t drop_type;
  /*
   * tse_key_type
   */
  int32_t key_type;
};
#define TC_DB__TSE_DDLALTER_TABLE_DROP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tc_db__tse_ddlalter_table_drop__descriptor) \
    , (char *)protobuf_c_empty_string, 0, 0 }


struct  TcDb__TseDDLAlterTableDropKey
{
  ProtobufCMessage base;
  char *name;
  /*
   * tse_alter_table_drop_type
   */
  int32_t drop_type;
  /*
   * tse_key_type
   */
  int32_t key_type;
};
#define TC_DB__TSE_DDLALTER_TABLE_DROP_KEY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tc_db__tse_ddlalter_table_drop_key__descriptor) \
    , (char *)protobuf_c_empty_string, 0, 0 }


struct  TcDb__TseDDLAlterTableAlterColumn
{
  ProtobufCMessage base;
  char *name;
  char *new_name;
  /*
   * SET_DEFAULT, DROP_DEFAULT, RENAME_COLUMN
   */
  uint32_t type;
  protobuf_c_boolean has_no_default;
  protobuf_c_boolean has_default;
  protobuf_c_boolean is_default_null;
  /*
   *    string default_data = 8;
   */
  char *default_text;
};
#define TC_DB__TSE_DDLALTER_TABLE_ALTER_COLUMN__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tc_db__tse_ddlalter_table_alter_column__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0, 0, 0, (char *)protobuf_c_empty_string }


struct  TcDb__TseDDLAlterTableDef
{
  ProtobufCMessage base;
  /*
   * altable_action_t
   */
  uint32_t action;
  uint32_t options;
  char *user;
  char *name;
  /*
   **
   *Columns, keys and constraints to be dropped.
   */
  size_t n_drop_list;
  TcDb__TseDDLAlterTableDrop **drop_list;
  /*
   * Columns for ALTER_COLUMN_CHANGE_DEFAULT.
   */
  size_t n_alter_list;
  TcDb__TseDDLAlterTableAlterColumn **alter_list;
  /*
   * List of columns, used by both CREATE and ALTER TABLE.
   */
  size_t n_create_list;
  TcDb__TseDDLColumnDef **create_list;
  TcDb__TseDDLAlterTablePorp *table_def;
  size_t n_add_key_list;
  TcDb__TseDDLTableKey **add_key_list;
  size_t n_drop_key_list;
  TcDb__TseDDLAlterTableDropKey **drop_key_list;
  size_t n_add_foreign_key_list;
  TcDb__TseDDLForeignKeyDef **add_foreign_key_list;
  uint64_t new_auto_increment_value;
  char *db_name;
  char *sql_str;
  size_t n_alter_index_list;
  TcDb__TseDDLAlterIndexDef **alter_index_list;
  size_t n_drop_partition_names;
  char **drop_partition_names;
  size_t n_add_part_list;
  TcDb__TseDDLPartitionTableDef **add_part_list;
  uint32_t hash_coalesce_count;
  int64_t systimestamp;
  int32_t tz_offset_utc;
  int32_t handler_trivial_ctx;
};
#define TC_DB__TSE_DDLALTER_TABLE_DEF__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tc_db__tse_ddlalter_table_def__descriptor) \
    , 0, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0,NULL, 0,NULL, 0,NULL, NULL, 0,NULL, 0,NULL, 0,NULL, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0,NULL, 0,NULL, 0,NULL, 0, 0, 0, 0 }


struct  TcDb__TseDDLTruncateTableDef
{
  ProtobufCMessage base;
  char *schema;
  char *name;
  char *db_name;
  char *sql_str;
  uint32_t no_check_fk;
};
#define TC_DB__TSE_DDLTRUNCATE_TABLE_DEF__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tc_db__tse_ddltruncate_table_def__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0 }


struct  TcDb__TseDDLTruncateTablePartitionDef
{
  ProtobufCMessage base;
  char *user;
  char *db_name;
  char *table_name;
  size_t n_partition_name;
  char **partition_name;
  size_t n_partition_id;
  uint32_t *partition_id;
  char *sql_str;
  protobuf_c_boolean is_subpart;
  size_t n_subpartition_name;
  char **subpartition_name;
  size_t n_subpartition_id;
  uint32_t *subpartition_id;
};
#define TC_DB__TSE_DDLTRUNCATE_TABLE_PARTITION_DEF__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tc_db__tse_ddltruncate_table_partition_def__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0,NULL, 0,NULL, (char *)protobuf_c_empty_string, 0, 0,NULL, 0,NULL }


struct  TcDb__TseDDLRenameTableDef
{
  ProtobufCMessage base;
  /*
   * altable_action_t
   */
  uint32_t action;
  uint32_t options;
  char *user;
  char *new_user;
  char *new_table_name;
  char *new_db_name;
  char *old_table_name;
  char *old_db_name;
  char *current_db_name;
  char *sql_str;
  size_t n_old_constraints_name;
  char **old_constraints_name;
  size_t n_new_constraints_name;
  char **new_constraints_name;
};
#define TC_DB__TSE_DDLRENAME_TABLE_DEF__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tc_db__tse_ddlrename_table_def__descriptor) \
    , 0, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0,NULL, 0,NULL }


struct  TcDb__TseDDLDropTableDef
{
  ProtobufCMessage base;
  uint32_t options;
  char *user;
  char *name;
  char *dbname_und;
  char *db_name;
  char *sql_str;
};
#define TC_DB__TSE_DDLDROP_TABLE_DEF__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tc_db__tse_ddldrop_table_def__descriptor) \
    , 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  TcDb__TseDDLAlterIndexDef
{
  ProtobufCMessage base;
  char *user;
  char *name;
  /*
   * def type
   */
  uint32_t type;
  char *table;
  char *new_name;
  /*
   * tse_key_type
   */
  int32_t key_type;
};
#define TC_DB__TSE_DDLALTER_INDEX_DEF__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tc_db__tse_ddlalter_index_def__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0 }


struct  TcDb__TseDDLAutoExtendDef
{
  ProtobufCMessage base;
  protobuf_c_boolean enabled;
  uint64_t nextsize;
  int64_t maxsize;
};
#define TC_DB__TSE_DDLAUTO_EXTEND_DEF__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tc_db__tse_ddlauto_extend_def__descriptor) \
    , 0, 0, 0 }


struct  TcDb__TseDDLDataFileDef
{
  ProtobufCMessage base;
  char *name;
  /*
   *device size
   */
  int64_t size;
  int32_t block_size;
  /*
   * the data of the autoextend property of the device
   */
  TcDb__TseDDLAutoExtendDef *autoextend;
  uint32_t node_id;
};
#define TC_DB__TSE_DDLDATA_FILE_DEF__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tc_db__tse_ddldata_file_def__descriptor) \
    , (char *)protobuf_c_empty_string, 0, 0, NULL, 0 }


struct  TcDb__TseDDLSpaceDef
{
  ProtobufCMessage base;
  /*
   * name of the space
   */
  char *name;
  /*
   * type of the space
   */
  uint32_t type;
  protobuf_c_boolean in_memory;
  protobuf_c_boolean autooffline;
  uint32_t extent_size;
  size_t n_datafiles_list;
  TcDb__TseDDLDataFileDef **datafiles_list;
  uint32_t flags;
  char *db_name;
  char *sql_str;
};
#define TC_DB__TSE_DDLSPACE_DEF__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tc_db__tse_ddlspace_def__descriptor) \
    , (char *)protobuf_c_empty_string, 0, 0, 0, 0, 0,NULL, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  TcDb__TseDDLDropSpaceDef
{
  ProtobufCMessage base;
  char *obj_name;
  uint32_t option;
  char *db_name;
  char *sql_str;
};
#define TC_DB__TSE_DDLDROP_SPACE_DEF__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tc_db__tse_ddldrop_space_def__descriptor) \
    , (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  TcDb__TseDDLAlterSpaceDef
{
  ProtobufCMessage base;
  uint32_t action;
  /*
   * name of the space
   */
  char *name;
  /*
   * name of the new space
   */
  char *new_name;
  uint64_t auto_extend_size;
  char *db_name;
  char *sql_str;
};
#define TC_DB__TSE_DDLALTER_SPACE_DEF__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tc_db__tse_ddlalter_space_def__descriptor) \
    , 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/* TcDb__TseDDLColumnDataTypeDef methods */
void   tc_db__tse_ddlcolumn_data_type_def__init
                     (TcDb__TseDDLColumnDataTypeDef         *message);
size_t tc_db__tse_ddlcolumn_data_type_def__get_packed_size
                     (const TcDb__TseDDLColumnDataTypeDef   *message);
size_t tc_db__tse_ddlcolumn_data_type_def__pack
                     (const TcDb__TseDDLColumnDataTypeDef   *message,
                      uint8_t             *out);
size_t tc_db__tse_ddlcolumn_data_type_def__pack_to_buffer
                     (const TcDb__TseDDLColumnDataTypeDef   *message,
                      ProtobufCBuffer     *buffer);
TcDb__TseDDLColumnDataTypeDef *
       tc_db__tse_ddlcolumn_data_type_def__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   tc_db__tse_ddlcolumn_data_type_def__free_unpacked
                     (TcDb__TseDDLColumnDataTypeDef *message,
                      ProtobufCAllocator *allocator);
/* TcDb__TseDDLColumnDef methods */
void   tc_db__tse_ddlcolumn_def__init
                     (TcDb__TseDDLColumnDef         *message);
size_t tc_db__tse_ddlcolumn_def__get_packed_size
                     (const TcDb__TseDDLColumnDef   *message);
size_t tc_db__tse_ddlcolumn_def__pack
                     (const TcDb__TseDDLColumnDef   *message,
                      uint8_t             *out);
size_t tc_db__tse_ddlcolumn_def__pack_to_buffer
                     (const TcDb__TseDDLColumnDef   *message,
                      ProtobufCBuffer     *buffer);
TcDb__TseDDLColumnDef *
       tc_db__tse_ddlcolumn_def__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   tc_db__tse_ddlcolumn_def__free_unpacked
                     (TcDb__TseDDLColumnDef *message,
                      ProtobufCAllocator *allocator);
/* TcDb__TseDDLForeignKeyElementDef methods */
void   tc_db__tse_ddlforeign_key_element_def__init
                     (TcDb__TseDDLForeignKeyElementDef         *message);
size_t tc_db__tse_ddlforeign_key_element_def__get_packed_size
                     (const TcDb__TseDDLForeignKeyElementDef   *message);
size_t tc_db__tse_ddlforeign_key_element_def__pack
                     (const TcDb__TseDDLForeignKeyElementDef   *message,
                      uint8_t             *out);
size_t tc_db__tse_ddlforeign_key_element_def__pack_to_buffer
                     (const TcDb__TseDDLForeignKeyElementDef   *message,
                      ProtobufCBuffer     *buffer);
TcDb__TseDDLForeignKeyElementDef *
       tc_db__tse_ddlforeign_key_element_def__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   tc_db__tse_ddlforeign_key_element_def__free_unpacked
                     (TcDb__TseDDLForeignKeyElementDef *message,
                      ProtobufCAllocator *allocator);
/* TcDb__TseDDLForeignKeyDef methods */
void   tc_db__tse_ddlforeign_key_def__init
                     (TcDb__TseDDLForeignKeyDef         *message);
size_t tc_db__tse_ddlforeign_key_def__get_packed_size
                     (const TcDb__TseDDLForeignKeyDef   *message);
size_t tc_db__tse_ddlforeign_key_def__pack
                     (const TcDb__TseDDLForeignKeyDef   *message,
                      uint8_t             *out);
size_t tc_db__tse_ddlforeign_key_def__pack_to_buffer
                     (const TcDb__TseDDLForeignKeyDef   *message,
                      ProtobufCBuffer     *buffer);
TcDb__TseDDLForeignKeyDef *
       tc_db__tse_ddlforeign_key_def__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   tc_db__tse_ddlforeign_key_def__free_unpacked
                     (TcDb__TseDDLForeignKeyDef *message,
                      ProtobufCAllocator *allocator);
/* TcDb__TseDDLTableKeyPart methods */
void   tc_db__tse_ddltable_key_part__init
                     (TcDb__TseDDLTableKeyPart         *message);
size_t tc_db__tse_ddltable_key_part__get_packed_size
                     (const TcDb__TseDDLTableKeyPart   *message);
size_t tc_db__tse_ddltable_key_part__pack
                     (const TcDb__TseDDLTableKeyPart   *message,
                      uint8_t             *out);
size_t tc_db__tse_ddltable_key_part__pack_to_buffer
                     (const TcDb__TseDDLTableKeyPart   *message,
                      ProtobufCBuffer     *buffer);
TcDb__TseDDLTableKeyPart *
       tc_db__tse_ddltable_key_part__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   tc_db__tse_ddltable_key_part__free_unpacked
                     (TcDb__TseDDLTableKeyPart *message,
                      ProtobufCAllocator *allocator);
/* TcDb__TseDDLTableKey methods */
void   tc_db__tse_ddltable_key__init
                     (TcDb__TseDDLTableKey         *message);
size_t tc_db__tse_ddltable_key__get_packed_size
                     (const TcDb__TseDDLTableKey   *message);
size_t tc_db__tse_ddltable_key__pack
                     (const TcDb__TseDDLTableKey   *message,
                      uint8_t             *out);
size_t tc_db__tse_ddltable_key__pack_to_buffer
                     (const TcDb__TseDDLTableKey   *message,
                      ProtobufCBuffer     *buffer);
TcDb__TseDDLTableKey *
       tc_db__tse_ddltable_key__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   tc_db__tse_ddltable_key__free_unpacked
                     (TcDb__TseDDLTableKey *message,
                      ProtobufCAllocator *allocator);
/* TcDb__TseMsgCommDef methods */
void   tc_db__tse_msg_comm_def__init
                     (TcDb__TseMsgCommDef         *message);
size_t tc_db__tse_msg_comm_def__get_packed_size
                     (const TcDb__TseMsgCommDef   *message);
size_t tc_db__tse_msg_comm_def__pack
                     (const TcDb__TseMsgCommDef   *message,
                      uint8_t             *out);
size_t tc_db__tse_msg_comm_def__pack_to_buffer
                     (const TcDb__TseMsgCommDef   *message,
                      ProtobufCBuffer     *buffer);
TcDb__TseMsgCommDef *
       tc_db__tse_msg_comm_def__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   tc_db__tse_msg_comm_def__free_unpacked
                     (TcDb__TseMsgCommDef *message,
                      ProtobufCAllocator *allocator);
/* TcDb__TseDDLPartitionTableDef methods */
void   tc_db__tse_ddlpartition_table_def__init
                     (TcDb__TseDDLPartitionTableDef         *message);
size_t tc_db__tse_ddlpartition_table_def__get_packed_size
                     (const TcDb__TseDDLPartitionTableDef   *message);
size_t tc_db__tse_ddlpartition_table_def__pack
                     (const TcDb__TseDDLPartitionTableDef   *message,
                      uint8_t             *out);
size_t tc_db__tse_ddlpartition_table_def__pack_to_buffer
                     (const TcDb__TseDDLPartitionTableDef   *message,
                      ProtobufCBuffer     *buffer);
TcDb__TseDDLPartitionTableDef *
       tc_db__tse_ddlpartition_table_def__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   tc_db__tse_ddlpartition_table_def__free_unpacked
                     (TcDb__TseDDLPartitionTableDef *message,
                      ProtobufCAllocator *allocator);
/* TcDb__TseDDLPartitionDef methods */
void   tc_db__tse_ddlpartition_def__init
                     (TcDb__TseDDLPartitionDef         *message);
size_t tc_db__tse_ddlpartition_def__get_packed_size
                     (const TcDb__TseDDLPartitionDef   *message);
size_t tc_db__tse_ddlpartition_def__pack
                     (const TcDb__TseDDLPartitionDef   *message,
                      uint8_t             *out);
size_t tc_db__tse_ddlpartition_def__pack_to_buffer
                     (const TcDb__TseDDLPartitionDef   *message,
                      ProtobufCBuffer     *buffer);
TcDb__TseDDLPartitionDef *
       tc_db__tse_ddlpartition_def__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   tc_db__tse_ddlpartition_def__free_unpacked
                     (TcDb__TseDDLPartitionDef *message,
                      ProtobufCAllocator *allocator);
/* TcDb__TseDDLCreateTableDef methods */
void   tc_db__tse_ddlcreate_table_def__init
                     (TcDb__TseDDLCreateTableDef         *message);
size_t tc_db__tse_ddlcreate_table_def__get_packed_size
                     (const TcDb__TseDDLCreateTableDef   *message);
size_t tc_db__tse_ddlcreate_table_def__pack
                     (const TcDb__TseDDLCreateTableDef   *message,
                      uint8_t             *out);
size_t tc_db__tse_ddlcreate_table_def__pack_to_buffer
                     (const TcDb__TseDDLCreateTableDef   *message,
                      ProtobufCBuffer     *buffer);
TcDb__TseDDLCreateTableDef *
       tc_db__tse_ddlcreate_table_def__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   tc_db__tse_ddlcreate_table_def__free_unpacked
                     (TcDb__TseDDLCreateTableDef *message,
                      ProtobufCAllocator *allocator);
/* TcDb__TseDDLAlterTablePorp methods */
void   tc_db__tse_ddlalter_table_porp__init
                     (TcDb__TseDDLAlterTablePorp         *message);
size_t tc_db__tse_ddlalter_table_porp__get_packed_size
                     (const TcDb__TseDDLAlterTablePorp   *message);
size_t tc_db__tse_ddlalter_table_porp__pack
                     (const TcDb__TseDDLAlterTablePorp   *message,
                      uint8_t             *out);
size_t tc_db__tse_ddlalter_table_porp__pack_to_buffer
                     (const TcDb__TseDDLAlterTablePorp   *message,
                      ProtobufCBuffer     *buffer);
TcDb__TseDDLAlterTablePorp *
       tc_db__tse_ddlalter_table_porp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   tc_db__tse_ddlalter_table_porp__free_unpacked
                     (TcDb__TseDDLAlterTablePorp *message,
                      ProtobufCAllocator *allocator);
/* TcDb__TseDDLAlterTableDrop methods */
void   tc_db__tse_ddlalter_table_drop__init
                     (TcDb__TseDDLAlterTableDrop         *message);
size_t tc_db__tse_ddlalter_table_drop__get_packed_size
                     (const TcDb__TseDDLAlterTableDrop   *message);
size_t tc_db__tse_ddlalter_table_drop__pack
                     (const TcDb__TseDDLAlterTableDrop   *message,
                      uint8_t             *out);
size_t tc_db__tse_ddlalter_table_drop__pack_to_buffer
                     (const TcDb__TseDDLAlterTableDrop   *message,
                      ProtobufCBuffer     *buffer);
TcDb__TseDDLAlterTableDrop *
       tc_db__tse_ddlalter_table_drop__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   tc_db__tse_ddlalter_table_drop__free_unpacked
                     (TcDb__TseDDLAlterTableDrop *message,
                      ProtobufCAllocator *allocator);
/* TcDb__TseDDLAlterTableDropKey methods */
void   tc_db__tse_ddlalter_table_drop_key__init
                     (TcDb__TseDDLAlterTableDropKey         *message);
size_t tc_db__tse_ddlalter_table_drop_key__get_packed_size
                     (const TcDb__TseDDLAlterTableDropKey   *message);
size_t tc_db__tse_ddlalter_table_drop_key__pack
                     (const TcDb__TseDDLAlterTableDropKey   *message,
                      uint8_t             *out);
size_t tc_db__tse_ddlalter_table_drop_key__pack_to_buffer
                     (const TcDb__TseDDLAlterTableDropKey   *message,
                      ProtobufCBuffer     *buffer);
TcDb__TseDDLAlterTableDropKey *
       tc_db__tse_ddlalter_table_drop_key__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   tc_db__tse_ddlalter_table_drop_key__free_unpacked
                     (TcDb__TseDDLAlterTableDropKey *message,
                      ProtobufCAllocator *allocator);
/* TcDb__TseDDLAlterTableAlterColumn methods */
void   tc_db__tse_ddlalter_table_alter_column__init
                     (TcDb__TseDDLAlterTableAlterColumn         *message);
size_t tc_db__tse_ddlalter_table_alter_column__get_packed_size
                     (const TcDb__TseDDLAlterTableAlterColumn   *message);
size_t tc_db__tse_ddlalter_table_alter_column__pack
                     (const TcDb__TseDDLAlterTableAlterColumn   *message,
                      uint8_t             *out);
size_t tc_db__tse_ddlalter_table_alter_column__pack_to_buffer
                     (const TcDb__TseDDLAlterTableAlterColumn   *message,
                      ProtobufCBuffer     *buffer);
TcDb__TseDDLAlterTableAlterColumn *
       tc_db__tse_ddlalter_table_alter_column__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   tc_db__tse_ddlalter_table_alter_column__free_unpacked
                     (TcDb__TseDDLAlterTableAlterColumn *message,
                      ProtobufCAllocator *allocator);
/* TcDb__TseDDLAlterTableDef methods */
void   tc_db__tse_ddlalter_table_def__init
                     (TcDb__TseDDLAlterTableDef         *message);
size_t tc_db__tse_ddlalter_table_def__get_packed_size
                     (const TcDb__TseDDLAlterTableDef   *message);
size_t tc_db__tse_ddlalter_table_def__pack
                     (const TcDb__TseDDLAlterTableDef   *message,
                      uint8_t             *out);
size_t tc_db__tse_ddlalter_table_def__pack_to_buffer
                     (const TcDb__TseDDLAlterTableDef   *message,
                      ProtobufCBuffer     *buffer);
TcDb__TseDDLAlterTableDef *
       tc_db__tse_ddlalter_table_def__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   tc_db__tse_ddlalter_table_def__free_unpacked
                     (TcDb__TseDDLAlterTableDef *message,
                      ProtobufCAllocator *allocator);
/* TcDb__TseDDLTruncateTableDef methods */
void   tc_db__tse_ddltruncate_table_def__init
                     (TcDb__TseDDLTruncateTableDef         *message);
size_t tc_db__tse_ddltruncate_table_def__get_packed_size
                     (const TcDb__TseDDLTruncateTableDef   *message);
size_t tc_db__tse_ddltruncate_table_def__pack
                     (const TcDb__TseDDLTruncateTableDef   *message,
                      uint8_t             *out);
size_t tc_db__tse_ddltruncate_table_def__pack_to_buffer
                     (const TcDb__TseDDLTruncateTableDef   *message,
                      ProtobufCBuffer     *buffer);
TcDb__TseDDLTruncateTableDef *
       tc_db__tse_ddltruncate_table_def__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   tc_db__tse_ddltruncate_table_def__free_unpacked
                     (TcDb__TseDDLTruncateTableDef *message,
                      ProtobufCAllocator *allocator);
/* TcDb__TseDDLTruncateTablePartitionDef methods */
void   tc_db__tse_ddltruncate_table_partition_def__init
                     (TcDb__TseDDLTruncateTablePartitionDef         *message);
size_t tc_db__tse_ddltruncate_table_partition_def__get_packed_size
                     (const TcDb__TseDDLTruncateTablePartitionDef   *message);
size_t tc_db__tse_ddltruncate_table_partition_def__pack
                     (const TcDb__TseDDLTruncateTablePartitionDef   *message,
                      uint8_t             *out);
size_t tc_db__tse_ddltruncate_table_partition_def__pack_to_buffer
                     (const TcDb__TseDDLTruncateTablePartitionDef   *message,
                      ProtobufCBuffer     *buffer);
TcDb__TseDDLTruncateTablePartitionDef *
       tc_db__tse_ddltruncate_table_partition_def__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   tc_db__tse_ddltruncate_table_partition_def__free_unpacked
                     (TcDb__TseDDLTruncateTablePartitionDef *message,
                      ProtobufCAllocator *allocator);
/* TcDb__TseDDLRenameTableDef methods */
void   tc_db__tse_ddlrename_table_def__init
                     (TcDb__TseDDLRenameTableDef         *message);
size_t tc_db__tse_ddlrename_table_def__get_packed_size
                     (const TcDb__TseDDLRenameTableDef   *message);
size_t tc_db__tse_ddlrename_table_def__pack
                     (const TcDb__TseDDLRenameTableDef   *message,
                      uint8_t             *out);
size_t tc_db__tse_ddlrename_table_def__pack_to_buffer
                     (const TcDb__TseDDLRenameTableDef   *message,
                      ProtobufCBuffer     *buffer);
TcDb__TseDDLRenameTableDef *
       tc_db__tse_ddlrename_table_def__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   tc_db__tse_ddlrename_table_def__free_unpacked
                     (TcDb__TseDDLRenameTableDef *message,
                      ProtobufCAllocator *allocator);
/* TcDb__TseDDLDropTableDef methods */
void   tc_db__tse_ddldrop_table_def__init
                     (TcDb__TseDDLDropTableDef         *message);
size_t tc_db__tse_ddldrop_table_def__get_packed_size
                     (const TcDb__TseDDLDropTableDef   *message);
size_t tc_db__tse_ddldrop_table_def__pack
                     (const TcDb__TseDDLDropTableDef   *message,
                      uint8_t             *out);
size_t tc_db__tse_ddldrop_table_def__pack_to_buffer
                     (const TcDb__TseDDLDropTableDef   *message,
                      ProtobufCBuffer     *buffer);
TcDb__TseDDLDropTableDef *
       tc_db__tse_ddldrop_table_def__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   tc_db__tse_ddldrop_table_def__free_unpacked
                     (TcDb__TseDDLDropTableDef *message,
                      ProtobufCAllocator *allocator);
/* TcDb__TseDDLAlterIndexDef methods */
void   tc_db__tse_ddlalter_index_def__init
                     (TcDb__TseDDLAlterIndexDef         *message);
size_t tc_db__tse_ddlalter_index_def__get_packed_size
                     (const TcDb__TseDDLAlterIndexDef   *message);
size_t tc_db__tse_ddlalter_index_def__pack
                     (const TcDb__TseDDLAlterIndexDef   *message,
                      uint8_t             *out);
size_t tc_db__tse_ddlalter_index_def__pack_to_buffer
                     (const TcDb__TseDDLAlterIndexDef   *message,
                      ProtobufCBuffer     *buffer);
TcDb__TseDDLAlterIndexDef *
       tc_db__tse_ddlalter_index_def__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   tc_db__tse_ddlalter_index_def__free_unpacked
                     (TcDb__TseDDLAlterIndexDef *message,
                      ProtobufCAllocator *allocator);
/* TcDb__TseDDLAutoExtendDef methods */
void   tc_db__tse_ddlauto_extend_def__init
                     (TcDb__TseDDLAutoExtendDef         *message);
size_t tc_db__tse_ddlauto_extend_def__get_packed_size
                     (const TcDb__TseDDLAutoExtendDef   *message);
size_t tc_db__tse_ddlauto_extend_def__pack
                     (const TcDb__TseDDLAutoExtendDef   *message,
                      uint8_t             *out);
size_t tc_db__tse_ddlauto_extend_def__pack_to_buffer
                     (const TcDb__TseDDLAutoExtendDef   *message,
                      ProtobufCBuffer     *buffer);
TcDb__TseDDLAutoExtendDef *
       tc_db__tse_ddlauto_extend_def__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   tc_db__tse_ddlauto_extend_def__free_unpacked
                     (TcDb__TseDDLAutoExtendDef *message,
                      ProtobufCAllocator *allocator);
/* TcDb__TseDDLDataFileDef methods */
void   tc_db__tse_ddldata_file_def__init
                     (TcDb__TseDDLDataFileDef         *message);
size_t tc_db__tse_ddldata_file_def__get_packed_size
                     (const TcDb__TseDDLDataFileDef   *message);
size_t tc_db__tse_ddldata_file_def__pack
                     (const TcDb__TseDDLDataFileDef   *message,
                      uint8_t             *out);
size_t tc_db__tse_ddldata_file_def__pack_to_buffer
                     (const TcDb__TseDDLDataFileDef   *message,
                      ProtobufCBuffer     *buffer);
TcDb__TseDDLDataFileDef *
       tc_db__tse_ddldata_file_def__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   tc_db__tse_ddldata_file_def__free_unpacked
                     (TcDb__TseDDLDataFileDef *message,
                      ProtobufCAllocator *allocator);
/* TcDb__TseDDLSpaceDef methods */
void   tc_db__tse_ddlspace_def__init
                     (TcDb__TseDDLSpaceDef         *message);
size_t tc_db__tse_ddlspace_def__get_packed_size
                     (const TcDb__TseDDLSpaceDef   *message);
size_t tc_db__tse_ddlspace_def__pack
                     (const TcDb__TseDDLSpaceDef   *message,
                      uint8_t             *out);
size_t tc_db__tse_ddlspace_def__pack_to_buffer
                     (const TcDb__TseDDLSpaceDef   *message,
                      ProtobufCBuffer     *buffer);
TcDb__TseDDLSpaceDef *
       tc_db__tse_ddlspace_def__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   tc_db__tse_ddlspace_def__free_unpacked
                     (TcDb__TseDDLSpaceDef *message,
                      ProtobufCAllocator *allocator);
/* TcDb__TseDDLDropSpaceDef methods */
void   tc_db__tse_ddldrop_space_def__init
                     (TcDb__TseDDLDropSpaceDef         *message);
size_t tc_db__tse_ddldrop_space_def__get_packed_size
                     (const TcDb__TseDDLDropSpaceDef   *message);
size_t tc_db__tse_ddldrop_space_def__pack
                     (const TcDb__TseDDLDropSpaceDef   *message,
                      uint8_t             *out);
size_t tc_db__tse_ddldrop_space_def__pack_to_buffer
                     (const TcDb__TseDDLDropSpaceDef   *message,
                      ProtobufCBuffer     *buffer);
TcDb__TseDDLDropSpaceDef *
       tc_db__tse_ddldrop_space_def__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   tc_db__tse_ddldrop_space_def__free_unpacked
                     (TcDb__TseDDLDropSpaceDef *message,
                      ProtobufCAllocator *allocator);
/* TcDb__TseDDLAlterSpaceDef methods */
void   tc_db__tse_ddlalter_space_def__init
                     (TcDb__TseDDLAlterSpaceDef         *message);
size_t tc_db__tse_ddlalter_space_def__get_packed_size
                     (const TcDb__TseDDLAlterSpaceDef   *message);
size_t tc_db__tse_ddlalter_space_def__pack
                     (const TcDb__TseDDLAlterSpaceDef   *message,
                      uint8_t             *out);
size_t tc_db__tse_ddlalter_space_def__pack_to_buffer
                     (const TcDb__TseDDLAlterSpaceDef   *message,
                      ProtobufCBuffer     *buffer);
TcDb__TseDDLAlterSpaceDef *
       tc_db__tse_ddlalter_space_def__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   tc_db__tse_ddlalter_space_def__free_unpacked
                     (TcDb__TseDDLAlterSpaceDef *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*TcDb__TseDDLColumnDataTypeDef_Closure)
                 (const TcDb__TseDDLColumnDataTypeDef *message,
                  void *closure_data);
typedef void (*TcDb__TseDDLColumnDef_Closure)
                 (const TcDb__TseDDLColumnDef *message,
                  void *closure_data);
typedef void (*TcDb__TseDDLForeignKeyElementDef_Closure)
                 (const TcDb__TseDDLForeignKeyElementDef *message,
                  void *closure_data);
typedef void (*TcDb__TseDDLForeignKeyDef_Closure)
                 (const TcDb__TseDDLForeignKeyDef *message,
                  void *closure_data);
typedef void (*TcDb__TseDDLTableKeyPart_Closure)
                 (const TcDb__TseDDLTableKeyPart *message,
                  void *closure_data);
typedef void (*TcDb__TseDDLTableKey_Closure)
                 (const TcDb__TseDDLTableKey *message,
                  void *closure_data);
typedef void (*TcDb__TseMsgCommDef_Closure)
                 (const TcDb__TseMsgCommDef *message,
                  void *closure_data);
typedef void (*TcDb__TseDDLPartitionTableDef_Closure)
                 (const TcDb__TseDDLPartitionTableDef *message,
                  void *closure_data);
typedef void (*TcDb__TseDDLPartitionDef_Closure)
                 (const TcDb__TseDDLPartitionDef *message,
                  void *closure_data);
typedef void (*TcDb__TseDDLCreateTableDef_Closure)
                 (const TcDb__TseDDLCreateTableDef *message,
                  void *closure_data);
typedef void (*TcDb__TseDDLAlterTablePorp_Closure)
                 (const TcDb__TseDDLAlterTablePorp *message,
                  void *closure_data);
typedef void (*TcDb__TseDDLAlterTableDrop_Closure)
                 (const TcDb__TseDDLAlterTableDrop *message,
                  void *closure_data);
typedef void (*TcDb__TseDDLAlterTableDropKey_Closure)
                 (const TcDb__TseDDLAlterTableDropKey *message,
                  void *closure_data);
typedef void (*TcDb__TseDDLAlterTableAlterColumn_Closure)
                 (const TcDb__TseDDLAlterTableAlterColumn *message,
                  void *closure_data);
typedef void (*TcDb__TseDDLAlterTableDef_Closure)
                 (const TcDb__TseDDLAlterTableDef *message,
                  void *closure_data);
typedef void (*TcDb__TseDDLTruncateTableDef_Closure)
                 (const TcDb__TseDDLTruncateTableDef *message,
                  void *closure_data);
typedef void (*TcDb__TseDDLTruncateTablePartitionDef_Closure)
                 (const TcDb__TseDDLTruncateTablePartitionDef *message,
                  void *closure_data);
typedef void (*TcDb__TseDDLRenameTableDef_Closure)
                 (const TcDb__TseDDLRenameTableDef *message,
                  void *closure_data);
typedef void (*TcDb__TseDDLDropTableDef_Closure)
                 (const TcDb__TseDDLDropTableDef *message,
                  void *closure_data);
typedef void (*TcDb__TseDDLAlterIndexDef_Closure)
                 (const TcDb__TseDDLAlterIndexDef *message,
                  void *closure_data);
typedef void (*TcDb__TseDDLAutoExtendDef_Closure)
                 (const TcDb__TseDDLAutoExtendDef *message,
                  void *closure_data);
typedef void (*TcDb__TseDDLDataFileDef_Closure)
                 (const TcDb__TseDDLDataFileDef *message,
                  void *closure_data);
typedef void (*TcDb__TseDDLSpaceDef_Closure)
                 (const TcDb__TseDDLSpaceDef *message,
                  void *closure_data);
typedef void (*TcDb__TseDDLDropSpaceDef_Closure)
                 (const TcDb__TseDDLDropSpaceDef *message,
                  void *closure_data);
typedef void (*TcDb__TseDDLAlterSpaceDef_Closure)
                 (const TcDb__TseDDLAlterSpaceDef *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor tc_db__tse_ddlcolumn_data_type_def__descriptor;
extern const ProtobufCMessageDescriptor tc_db__tse_ddlcolumn_def__descriptor;
extern const ProtobufCMessageDescriptor tc_db__tse_ddlforeign_key_element_def__descriptor;
extern const ProtobufCMessageDescriptor tc_db__tse_ddlforeign_key_def__descriptor;
extern const ProtobufCMessageDescriptor tc_db__tse_ddltable_key_part__descriptor;
extern const ProtobufCMessageDescriptor tc_db__tse_ddltable_key__descriptor;
extern const ProtobufCMessageDescriptor tc_db__tse_msg_comm_def__descriptor;
extern const ProtobufCMessageDescriptor tc_db__tse_ddlpartition_table_def__descriptor;
extern const ProtobufCMessageDescriptor tc_db__tse_ddlpartition_def__descriptor;
extern const ProtobufCMessageDescriptor tc_db__tse_ddlcreate_table_def__descriptor;
extern const ProtobufCMessageDescriptor tc_db__tse_ddlalter_table_porp__descriptor;
extern const ProtobufCMessageDescriptor tc_db__tse_ddlalter_table_drop__descriptor;
extern const ProtobufCMessageDescriptor tc_db__tse_ddlalter_table_drop_key__descriptor;
extern const ProtobufCMessageDescriptor tc_db__tse_ddlalter_table_alter_column__descriptor;
extern const ProtobufCMessageDescriptor tc_db__tse_ddlalter_table_def__descriptor;
extern const ProtobufCMessageDescriptor tc_db__tse_ddltruncate_table_def__descriptor;
extern const ProtobufCMessageDescriptor tc_db__tse_ddltruncate_table_partition_def__descriptor;
extern const ProtobufCMessageDescriptor tc_db__tse_ddlrename_table_def__descriptor;
extern const ProtobufCMessageDescriptor tc_db__tse_ddldrop_table_def__descriptor;
extern const ProtobufCMessageDescriptor tc_db__tse_ddlalter_index_def__descriptor;
extern const ProtobufCMessageDescriptor tc_db__tse_ddlauto_extend_def__descriptor;
extern const ProtobufCMessageDescriptor tc_db__tse_ddldata_file_def__descriptor;
extern const ProtobufCMessageDescriptor tc_db__tse_ddlspace_def__descriptor;
extern const ProtobufCMessageDescriptor tc_db__tse_ddldrop_space_def__descriptor;
extern const ProtobufCMessageDescriptor tc_db__tse_ddlalter_space_def__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_tc_5fdb_2eproto__INCLUDED */
